import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { generateTypes, generateTypesFromFile } from "../dist/index.js";

describe("generateTypes", () => {
	it("generates header with manifest name and version", () => {
		const result = generateTypes({ xript: "0.1", name: "test-app", version: "1.0.0" });
		assert.ok(result.includes("// Source manifest: test-app v1.0.0"));
		assert.ok(result.includes("// Auto-generated by @xript/typegen"));
	});

	it("generates header without version when omitted", () => {
		const result = generateTypes({ xript: "0.1", name: "test-app" });
		assert.ok(result.includes("// Source manifest: test-app"));
		assert.ok(!result.includes(" v"));
	});

	it("supports custom header", () => {
		const result = generateTypes(
			{ xript: "0.1", name: "test-app" },
			{ header: "// Custom header" },
		);
		assert.ok(result.includes("// Custom header"));
		assert.ok(!result.includes("// Auto-generated"));
	});

	it("generates interface for object types", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			types: {
				Position: {
					description: "A 2D position.",
					fields: {
						x: { type: "number", description: "Horizontal." },
						y: { type: "number", description: "Vertical." },
					},
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("interface Position {"));
		assert.ok(result.includes("x: number;"));
		assert.ok(result.includes("y: number;"));
		assert.ok(result.includes("* A 2D position."));
		assert.ok(result.includes("* Horizontal."));
	});

	it("generates optional fields", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			types: {
				Item: {
					description: "An item.",
					fields: {
						id: { type: "string" },
						damage: { type: "number", optional: true },
					},
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("id: string;"));
		assert.ok(result.includes("damage?: number;"));
	});

	it("generates string literal union for enum types", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			types: {
				Direction: {
					description: "A cardinal direction.",
					values: ["north", "south", "east", "west"],
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes('type Direction = "north" | "south" | "east" | "west";'));
	});

	it("generates top-level function binding", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				log: {
					description: "Logs a message.",
					params: [{ name: "message", type: "string", description: "The message." }],
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("declare function log(message: string): void;"));
		assert.ok(result.includes("* Logs a message."));
		assert.ok(result.includes("@param message - The message."));
	});

	it("generates namespace binding", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				player: {
					description: "Player functions.",
					members: {
						getHealth: {
							description: "Returns health.",
							returns: "number",
						},
					},
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("declare namespace player {"));
		assert.ok(result.includes("function getHealth(): number;"));
	});

	it("generates async return types wrapped in Promise", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				fetchData: {
					description: "Fetches data.",
					returns: "string",
					async: true,
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("declare function fetchData(): Promise<string>;"));
	});

	it("includes capability annotation in JSDoc", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				setHealth: {
					description: "Sets health.",
					params: [{ name: "value", type: "number" }],
					capability: "modify-player",
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("@remarks Requires capability: `modify-player`"));
	});

	it("includes deprecated annotation", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				getHP: {
					description: "Returns health.",
					returns: "number",
					deprecated: "Use getHealth() instead.",
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("@deprecated Use getHealth() instead."));
	});

	it("handles optional parameters with default values", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				greet: {
					description: "Greets someone.",
					params: [
						{ name: "name", type: "string" },
						{ name: "excited", type: "boolean", default: false },
					],
					returns: "string",
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("declare function greet(name: string, excited?: boolean): string;"));
	});

	it("handles optional parameters with required: false", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				search: {
					description: "Searches.",
					params: [
						{ name: "query", type: "string" },
						{ name: "limit", type: "number", required: false },
					],
					returns: "string[]",
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("declare function search(query: string, limit?: number): string[];"));
	});

	it("resolves complex type: array object form", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				getItems: {
					description: "Gets items.",
					returns: { array: "Item" },
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("declare function getItems(): Item[];"));
	});

	it("resolves complex type: union", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				getValue: {
					description: "Gets a value.",
					returns: { union: ["string", "number"] },
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("declare function getValue(): string | number;"));
	});

	it("resolves complex type: map", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				getScores: {
					description: "Gets scores.",
					returns: { map: "number" },
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("declare function getScores(): Record<string, number>;"));
	});

	it("resolves complex type: optional", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				findUser: {
					description: "Finds a user.",
					params: [{ name: "id", type: "string" }],
					returns: { optional: "string" },
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("declare function findUser(id: string): string | undefined;"));
	});

	it("resolves shorthand array type (string[])", () => {
		const manifest = {
			xript: "0.1",
			name: "test",
			bindings: {
				getTags: {
					description: "Gets tags.",
					returns: "string[]",
				},
			},
		};
		const result = generateTypes(manifest);
		assert.ok(result.includes("declare function getTags(): string[];"));
	});

	it("generates full output for the dungeon-crawler example", async () => {
		const result = await generateTypesFromFile("../../examples/game-mod-system/manifest.json");
		assert.ok(result.content.includes("interface Position {"));
		assert.ok(result.content.includes("interface Item {"));
		assert.ok(result.content.includes("interface Enemy {"));
		assert.ok(result.content.includes('type ItemType = "weapon"'));
		assert.ok(result.content.includes('type EnemyType = "skeleton"'));
		assert.ok(result.content.includes("declare function log("));
		assert.ok(result.content.includes("declare namespace player {"));
		assert.ok(result.content.includes("declare namespace world {"));
		assert.ok(result.content.includes("declare namespace data {"));
		assert.ok(result.content.includes("Promise<Enemy[]>"));
		assert.ok(result.content.includes("Promise<string | undefined>"));
	});

	it("produces empty output for minimal manifest", () => {
		const result = generateTypes({ xript: "0.1", name: "minimal" });
		assert.ok(result.includes("// Source manifest: minimal"));
		assert.ok(!result.includes("declare"));
		assert.ok(!result.includes("interface"));
		assert.ok(!result.includes("type "));
	});
});
